---

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE =~ /^trigger|pipeline|web|api$/'
      when: always
    - if: $CI_COMMIT_TAG
      when: never
    - when: always


include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  # - template: Security/Container-Scanning.gitlab-ci.yml

  - local: 'ci/semantic-release.yml'

# Global SAST Variables

variables:
  SAST_EXCLUDED_PATHS: "spec,test,tests,tmp,node_modules,target,venv"
  SAST_BANDIT_EXCLUDED_PATHS: "*/test/**,*/tests/**,*/node_modules/**,*/target/**,*/venv/**"
  SECRET_DETECTION_EXCLUDED_PATHS: "docs"
  PYTHON_IMAGE: "python"
  PYTHON_TAG: "3.10"

  ## Semantic Release
  ENABLE_SEMANTIC_RELEASE: "true"
  ENABLE_SEMANTIC_RELEASE_DRY_RUN: "true"

stages:
- test
- build
- deploy
- publish

.base-python:
  image: $PYTHON_IMAGE:$PYTHON_TAG
  before_script:
    - pip install poetry
    - poetry install


###########
# test
###########

check-lint:
  extends: .base-python
  stage: test
  needs: []
  script:
    - poetry run pylint ./hoppr_cyclonedx_models

###########
# build
###########

build-dist:
  extends: .base-python
  stage: build
  needs: ["semantic-release:dry-run"]
  script:
    - sed -i -e "s/^__version__ = \".*\"/__version__ = \"$RELEASE_VERSION\"/" ./hoppr_cyclonedx_models/__init__.py 
    - poetry version $RELEASE_VERSION
    - poetry build
  artifacts:
    paths:
      - dist/
      - ./hoppr_cyclonedx_models/__init__.py 
      - pyproject.toml

generate-mod:
  extends: .base-python
  stage: build
  needs: ["semantic-release:dry-run"]
  script:
    - . model-gen.sh
  artifacts:
    paths:
      - $CI_PROJECT_DIR

###########
# docs
###########
# pages-review:
#   cache:
#     paths:
#     - apt-cache/
#   image: "ubuntu:jammy-20220428"
#   stage: docs
#   needs:
#     - job: semantic-release:dry-run
#       artifacts: true
#   variables:
#     PUBLIC_URL: "/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public"
#   environment:
#     name: review/$CI_COMMIT_REF_SLUG
#     url: "https://lmco.gitlab.io/-/hoppr/hoppr/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
#     auto_stop_in: 1 week
#   script:
#     - !reference [".setup_pages", "script"]
#     - !reference [".base-python", "before_script"]
#     - /bin/yq eval ".extra.hoppr.version = \"$RELEASE_VERSION\"" -i mkdocs.yml
#     - yarn install
#     - yarn run make:hoppr
#   artifacts:
#     expose_as: 'Hoppr Docs Preview'
#     paths:
#     - public
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       when: never
#     - if: '$CI_PIPELINE_SOURCE == "schedule"'
#       when: never
#     - if: $CI_COMMIT_REF_NAME != "main"


###########
# deploy
###########
semantic-release:
  stage: deploy

publish-whl:
  stage: publish
  extends: .base-python
  needs: ["semantic-release", "build-dist"]
  script:
    - poetry config repositories.gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
    - poetry publish --repository gitlab --username gitlab-ci-token --password "${CI_JOB_TOKEN}"
  artifacts:
    paths:
      - dist/
      - ./hoppr_cyclonedx_models/__init__.py 
      - pyproject.toml
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $ENABLE_SEMANTIC_RELEASE == "true" && $CI_PROJECT_NAMESPACE =~ /^lmco/'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never

