---
branches:
- main
publish:
  - "@semantic-release/gitlab"
plugins:
- - "@semantic-release/commit-analyzer"
  - preset: conventionalcommits
    releaseRules:
    - type: docs
      release: patch
    - type: refactor
      release: patch
    - type: style
      release: patch
    - type: bug
      release: patch
    parserOpts:
      noteKeywords:
      - BREAKING CHANGE
      - BREAKING CHANGES

- - "@semantic-release/release-notes-generator"
  - preset: conventionalcommits

- - "@semantic-release/exec"
  - generateNotesCmd: "echo RELEASE_VERSION=v${nextRelease.version} > release.env"

- - "@semantic-release/changelog"
  - changelogFile: docs/CHANGELOG.md

- - "@semantic-release/exec"
  - prepareCmd: |
      sed --in-place 's/__version__ = ".*"/__version__ = "${nextRelease.version}"/' hoppr_cyclonedx_models/__init__.py
      poetry lock --no-update
      poetry version ${nextRelease.version}

- - "@semantic-release/git"
  - assets:
    - docs/CHANGELOG.md
    - hoppr_cyclonedx_models/
    - pyproject.toml
    - yarn.lock

- - "@semantic-release/gitlab"
  - gitlabUrl: https://gitlab.com
    gitlabApiPathPrefix: "/api/v4"
    assets:
    - path: dist/hoppr_cyclonedx_models-*-py3-none-any.whl
      label: "CycloneDX Models Wheel"
    - path: dist/hoppr-cyclonedx-models-*.tar.gz
      label: "CycloneDX Models Installable Tar"
    - path: LICENSE
      label: LICENSE